#! zsh

function()
{
  if has-keg nvm; then
    mkdir -p "${HOME}"/.nvm
    export NVM_DIR="${HOME}/.nvm"
    source "$(brew --prefix nvm)/nvm.sh"
  elif [ -s "${HOME}"/.nvm/nvm.sh ]; then
    if [ -n "${XDG_CONFIG_HOME}" ]; then
      export NVM_DIR="${XDG_CONFIG_HOME}/nvm"
    else
      export NVM_DIR="${HOME}/.nvm"
    fi
    source "${NVM_DIR}/nvm.sh"
  fi
}
