#! zsh

function()
{
  if has-command ag; then
    function _ag()
    {
      if (( CURRENT == 2 )); then
        compadd $(cut -f 1 tmp/tags .git/tags 2>/dev/null)
      else;
        _files
      fi
    }

    compdef _ag ag
  fi
}
