---
# source-file: target-file
config/NuGet.Config: .config/NuGet/NuGet.Config
config/aws-config: .aws/config
config/aws-credentials: .aws/credentials
config/gem-credentials.yml: .gem/credentials
config/gitk: .config/git/gitk
config/gnupg: .gnupg/gpg.conf
config/htoprc: .config/htop/htoprc
config/hub: .config/hub
config/kitty.conf: .config/kitty/kitty.conf
config/ssh-config: .ssh/config
config/starship.toml: .config/starship.toml
fish: .config/fish
