---
# source-file: target-file
config/ssh-config: .ssh/config
config/gnupg: .gnupg/gpg.conf
config/hub: .config/hub
config/gem-credentials.yml: .gem/credentials
config/aws-credentials: .aws/credentials
config/aws-config: .aws/config
