#!/bin/zsh

function()
{
  local -A known_zsh_options
  known_zsh_options=($(builtin set -o))

  function --hz-setopt()
  {
    local opt_name=$(echo ${(L)1#no_#} | sed -e 's/_//g')
    if [ -n "${known_zsh_options[${opt_name}]}" ]; then
      builtin setopt ${1}
    fi
  }

  # Reorganized to match the zshoptions manpage; rather than ordering by
  # alphabetical sort, ordered by alphabetical within the logical groups.

  # [ changing directories ]
  --hz-setopt AUTO_CD                   # cd 'path' if 'path' is given as a command.
  --hz-setopt AUTO_PUSHD                # cd = pushd
  --hz-setopt NO_CDABLE_VARS            # don't try to expand as ~path
  --hz-setopt CHASE_DOTS                # implied by CHASE_LINKS
  --hz-setopt CHASE_LINKS               # cd to a symlink is in fact cd to the true dir
  --hz-setopt NO_POSIX_CD               # use zsh chdir
  --hz-setopt PUSHD_IGNORE_DUPS         # ignore dups in pushd
  --hz-setopt NO_PUSHD_MINUS            # don't exchange +/-
  --hz-setopt PUSHD_SILENT              # don't print stack after push/pop
  --hz-setopt PUSHD_TO_HOME             # pushd == pushd $HOME

  # [ completion ]
  --hz-setopt NO_ALWAYS_LAST_PROMPT     # Completions return to last prompt if numeric.
  --hz-setopt ALWAYS_TO_END             # Always go to end of word after completion.
  --hz-setopt AUTO_LIST                 # list choice on ambiguous command*
  --hz-setopt AUTO_MENU                 # show menu for completion*
  --hz-setopt NO_AUTO_NAME_DIRS         # Dir params are explicit ~param. RTFM.
  --hz-setopt AUTO_PARAM_KEYS           # Remove trailing spaces on param name completion*
  --hz-setopt AUTO_PARAM_SLASH          # add slash for directories*
  --hz-setopt AUTO_REMOVE_SLASH         # remove slash on dirs if word separator added*
  --hz-setopt NO_BASH_AUTO_LIST         # auto_list is sufficient, i want it on first tab
  --hz-setopt COMPLETE_ALIASES          # don't replace alias before completion
  --hz-setopt COMPLETE_IN_WORD          # completion to be done from cursor in word
  --hz-setopt NO_GLOB_COMPLETE          # don't generate matches and cycle through them
  --hz-setopt HASH_LIST_ALL             # verify path hash on completion*
  --hz-setopt LIST_AMBIGUOUS            # unambiguous prefix completion is done silently*
  --hz-setopt NO_LIST_BEEP              # don't beep for completion
  --hz-setopt LIST_PACKED               # different width for completion
  --hz-setopt LIST_ROWS_FIRST           # complete matches across, then down.
  --hz-setopt LIST_TYPES                # show types of listing files*
  --hz-setopt NO_MENU_COMPLETE          # don't show menu on ambiguous completion
  --hz-setopt NO_REC_EXACT              # recognize exact match even if ambiguous

  # [ expansion and globbing ]
  --hz-setopt BAD_PATTERN               # warn on bad file patterns*
  --hz-setopt BARE_GLOB_QUAL            # PATTERN()$ is a qualifier list*
  --hz-setopt BRACE_CCL                 # expand {adasd} to (a, d, s)
  --hz-setopt CASE_GLOB                 # case sensitive globbing*
  --hz-setopt CASE_MATCH                # regular expressions are case sensitive*
  --hz-setopt NO_CSH_NULL_GLOB          # don't erase unmatched globs silently
  --hz-setopt EQUALS                    # perform '=' file expansions*
  --hz-setopt EXTENDED_GLOB             # #,~,^ expansion
  --hz-setopt NO_FORCE_FLOAT            # do not convert to float for math
  --hz-setopt GLOB                      # sure i want globbing*
  --hz-setopt NO_GLOB_ASSIGN            # no globbing on foo=*, use foo=(*)
  --hz-setopt NO_GLOB_DOTS              # foo won't match .foo
  --hz-setopt GLOB_STAR_SHORT           # **/* => **; ***/* => ***.
  --hz-setopt NO_GLOB_SUBST             # no recursive expansion
  --hz-setopt NO_HIST_SUBST_PATTERN     # history substitution uses string matching
  --hz-setopt NO_IGNORE_BRACES          # do braces expansion
  --hz-setopt NO_IGNORE_CLOSE_BRACES    # Close braces are syntactically significatn
  --hz-setopt NO_KSH_GLOB               # ignore @ before ()
  --hz-setopt MAGIC_EQUAL_SUBST         # foo= is file expanded
  --hz-setopt MARK_DIRS                 # adds / on dirs in filename completion
  --hz-setopt MULTIBYTE                 # respect multibyte characters when found*
  --hz-setopt NOMATCH                   # print error on non matched patterns (!!!)*
  --hz-setopt NO_NULL_GLOB              # don't delete unmatched globs
  --hz-setopt NUMERIC_GLOB_SORT         # sort in numeric order rather than lexicographic
  --hz-setopt RC_EXPAND_PARAM           # foo${xx}bar where xx is (a b c) = fooabar ...
  --hz-setopt REMATCH_PCRE              # Use PCRE matching with =~.*
  --hz-setopt NO_SH_GLOB                # allow globbing with [(|)<]
  --hz-setopt UNSET                     # unset parameters are empty, not parameters.*
  --hz-setopt NO_WARN_CREATE_GLOBAL     # No warning on assigned global param in function.

  # [ history ]
  --hz-setopt APPEND_HISTORY             # append to history, don't truncate it*
  --hz-setopt BANG_HIST                  # csh-style history expansion with '!'*
  --hz-setopt EXTENDED_HISTORY           # no ttimestamped history (:time:elapsed:command)
  --hz-setopt HIST_ALLOW_CLOBBER         # add | to redirections in history
  --hz-setopt NO_HIST_BEEP               # don't beep on history expansion errors
  --hz-setopt HIST_EXPIRE_DUPS_FIRST     # remove dups from history first
  --hz-setopt HIST_FCNTL_LOCK            # use zsh's built-in ad-hoc history locking.
  --hz-setopt HIST_FIND_NO_DUPS          # don't show dups even if not contiguous
  --hz-setopt HIST_IGNORE_ALL_DUPS       # ignore all -- even non contiguous -- dups
  --hz-setopt HIST_IGNORE_DUPS           # ignore contiguous dups
  --hz-setopt HIST_IGNORE_SPACE          # store commands that match /^[^ ]/
  --hz-setopt HIST_LEX_WORDS             # use normal lexing on loaded history
  --hz-setopt HIST_NO_FUNCTIONS          # don't save functions defs in history
  --hz-setopt HIST_NO_STORE              # remove hists access cmds from hist
  --hz-setopt HIST_REDUCE_BLANKS         # remove superfluous blanks
  --hz-setopt HIST_SAVE_BY_COPY          # prevents history loss
  --hz-setopt HIST_SAVE_NO_DUPS          # no dups on history saving
  --hz-setopt HIST_VERIFY                # expands history into the edit buffer
  --hz-setopt NO_INC_APPEND_HISTORY      # append incrementally, not on exit
  --hz-setopt NO_INC_APPEND_HISTORY_TIME # append incrementally, not on exit, with time
  --hz-setopt SHARE_HISTORY              # Share history between sessions.

  # [ initialization ]
  --hz-setopt NO_ALL_EXPORT             # Parameters are not automatically exported
  --hz-setopt NO_GLOBAL_EXPORT          # declare -x does not imply -g
  --hz-setopt GLOBAL_RCS                # use global rcs*
  --hz-setopt RCS                       # source all /etc rcs

  # [ input/output ]
  --hz-setopt ALIASES                   # expand aliases
  --hz-setopt CLOBBER                   # redirection will truncate existing files*
  --hz-setopt CORRECT                   # try to spell-correct command line
  --hz-setopt NO_CORRECT_ALL            # don't correct args
  --hz-setopt NO_DVORAK                 # use only regular keyboard for correct
  --hz-setopt NO_FLOW_CONTROL           # ignore ^S/^Q as remnants of sttys.
  --hz-setopt NO_IGNORE_EOF             # don't ignore ^D for exit
  --hz-setopt INTERACTIVE_COMMENTS      # allow comments in interactive shell (!!!)
  --hz-setopt HASH_CMDS                 # do not always search through path, hash cmds*
  --hz-setopt HASH_DIRS                 # hash directories holding commands too*
  --hz-setopt NO_HASH_EXECUTABLES_ONLY  # do not check that the command is +x
  --hz-setopt NO_MAIL_WARNING           # no warning printed if mail file touched
  --hz-setopt PATH_DIRS                 # search in path even if cmd has '/' in it
  --hz-setopt NO_PATH_SCRIPT            # Don't search $PATH for a "zsh SCRIPT" cmd.
  --hz-setopt PRINT_EIGHT_BIT           # just to be sure
  --hz-setopt NO_PRINT_EXIT_VALUE       # Don't print exit values ($PROMPT does)
  --hz-setopt RC_QUOTES                 # 'foo''bar' => foo'bar
  --hz-setopt NO_RM_STAR_SILENT         # ask user before rm foo/*
  --hz-setopt RM_STAR_WAIT              # Make *really* sure. ~10s wait.
  --hz-setopt SHORT_LOOPS               # short loops forms allowed.*
  --hz-setopt NO_SUN_KEYBOARD_HACK      # I don't use a SUN keyboard.

  # [ job control ]
  --hz-setopt AUTO_CONTINUE             # send SIGCONT to jobs disowned
  --hz-setopt AUTO_RESUME               # single word resume if possible
  --hz-setopt NO_BG_NICE                # don't renice jobs in bg
  --hz-setopt CHECK_JOBS                # check jobs on exit*
  --hz-setopt NO_HUP                    # don't SIGHUP bg cmds on logout
  --hz-setopt LONG_LIST_JOBS            # list jobs in long format
  --hz-setopt MONITOR                   # enable job control
  --hz-setopt NOTIFY                    # notify immediately, not on next prompt*
  --hz-setopt NO_POSIX_JOBS             # Use zsh job management semantics.

  # [ prompting ]
  --hz-setopt NO_PROMPT_BANG            # don't perform history expansion in prompt
  --hz-setopt PROMPT_CR                 # ensure multi-line editing works.*
  --hz-setopt PROMPT_SP                 # preserve partial lines*
  --hz-setopt PROMPT_PERCENT            # expand % escapes in prompt*
  --hz-setopt PROMPT_SUBST              # command/math subst in prompt
  --hz-setopt TRANSIENT_RPROMPT         # better for cut/paste

  # [ scripts and functions ]
  --hz-setopt C_BASES                   # use C-style 0xff instead of 16#ff.
  --hz-setopt NO_C_PRECEDENCES          # Use zsh math evaluation order
  --hz-setopt DEBUG_BEFORE_CMD          # run DEBUG trap before command (ksh93)*
  #--hz-setopt err_exit                 # exit shell on unhandled error
  #--hz-setopt err_return               # return from function on unhandled error.
  --hz-setopt eval_lineno               # Track eval line numbers.*
  #--hz-setopt no_exec                  # syntax check only. scripts only.
  --hz-setopt function_argzero          # $0 == name of script*
  #--hz-setopt local_loops              # break/continue is local to a function
  #--hz-setopt local_options            # setopts are local to functions
  #--hz-setopt local_patterns           # restore `disable -p` pattern disable status
  #--hz-setopt local_traps              # traps are local to functions
  #--hz-setopt multi_func_def           # allow multiple function definition at once*
  --hz-setopt multios                   # multi redirection (implicit tee/cat)*
  --hz-setopt no_octal_zeroes           # 010 = 9 sucks
  #--hz-setopt pipe_fail                 # pipeline failure is non-zero fail command, not overall
  #--hz-setopt source_trace             # tracing similar to 'set -x'
  #--hz-setopt typeset_silent           # don't print values from typeset family
  #--hz-setopt verbose                  # Print input lines as they are read
  #--hz-setopt no_xtrace                # do not debug by default

  # [ shell emulation ]
  #--hz-setopt append_create            # redirection with append will create new files
  --hz-setopt no_bash_rematch           # use $MATCH/$match, not $BASH_REMATCH
  --hz-setopt no_bsd_echo               # use zsh echo, not BSD echo(1).
  #--hz-setopt no_continue_on_error     # do not act like interactive shell
  --hz-setopt no_csh_junkie_history     # zsh history references, not csh.
  --hz-setopt no_csh_junkie_loops       # zsh 'do list; done' not csh 'list; end'
  --hz-setopt no_csh_junkie_quotes      # csh quote rules are painful
  --hz-setopt no_csh_nullcmd            # keep my (READ)?NULLCMD for bare redirs.
  --hz-setopt no_ksh_arrays             # don't emulate ksh arrays
  --hz-setopt no_ksh_autoload           # zsh autoload (contents), not ksh autoload (exec)
  --hz-setopt no_ksh_option_print       # use zsh default 'setopt' output.
  --hz-setopt no_ksh_typeset            # use zsh typeset
  --hz-setopt no_ksh_zero_subscript     # use zsh array references (1-index)
  --hz-setopt no_posix_aliases          # use zsh alias expansion
  #--hz-setopt posix_argzero            # temporarily disable FUNCTION_ARGZERO
  --hz-setopt no_posix_builtins         # use zsh builtin semantics
  --hz-setopt no_posix_identifiers      # use zsh identifiers (allow -)
  --hz-setopt no_posix_strings          # use zsh string $'…' NUL handling
  --hz-setopt no_posix_traps            # use zsh EXIT traps when leaving functions

  --hz-setopt no_sh_file_expansion      # use zsh expansion precedence
  --hz-setopt no_sh_nullcmd             # use (READ)?NULLCMD, not :.
  --hz-setopt no_sh_option_letters      # don't interpret single option letters
  --hz-setopt no_sh_word_split          # `s="a b"; a=($s)' => array of length 1, not 2
  --hz-setopt traps_async               # Handle traps immediately, not on child exit.

  # [ shell state ]
  #--hz-setopt interactive              # Use the default
  #--hz-setopt login                    # Use the default
  #--hz-setopt privileged               # Use the default
  #--hz-setopt restricted               # Use the default
  #--hz-setopt shin_stdin               # Use the default
  #--hz-setopt single_command           # Use the default

  # [ zle ]
  --hz-setopt no_beep                   # beep on ZLE error
  --hz-setopt combining_chars           # handle multibyte combining chars right
  --hz-setopt no_emacs                  # let `bindkey` setup choose this
  --hz-setopt no_overstrike             # don't start ZLE in overstrike mode
  --hz-setopt no_single_line_zle        # use multiline editor
  --hz-setopt no_vi                     # let `bindkey` setup choose this
  --hz-setopt zle                       # use ZLE

  unfunction -- --hz-setopt
}
