#!/bin/zsh

autoload -U unique-path unique-manpath clean-path clean-manpath

if [ ${UID} -eq 0 ]; then
  add-paths-before-if ~root/bin
else
  # Other installs
  add-paths-before-if /usr/local/bin /usr/local/sbin
  [ -d /usr/local/man ] && unique-manpath -b /usr/local/man
  [ -d /usr/local/share/man ] && unique-manpath -b /usr/local/share/man

  # MacPorts
  add-paths-before-if /opt/local/bin /opt/local/sbin
  [ -d /opt/local/man ] && unique-manpath -b /opt/local/man
  [ -d /opt/local/share/man ] && unique-manpath -b /opt/local/share/man

  add-paths-before-if /opt/bin /opt/sbin
  [ -d /opt/man ] && unique-manpath -b /opt/man
  [ -d /opt/share/man ] && unique-manpath -b /opt/share/man

  if [ -x ${HOME}/usr/bin/git ]; then
    # Remove /usr/local/git, then add ${HOME}/usr/bin et al.
    clean-path /usr/local/git/bin
    clean-manpath /usr/local/git/man
    unique-path -b ${HOME}/usr/bin
    unique-manpath -b ${HOME}/usr/share/man
    export GIT_EXEC_PATH="${HOME}/usr/bin"
  else
    # Local system git
    add-paths-before-if /usr/local/git/bin
    [ -d /usr/local/git/man ] && unique-manpath -b /usr/local/git/man
  fi

  add-paths-before-if ${HOME}/.dotfiles/bin
  add-paths-before-if ${HOME}/.dotfiles/zsh/${OSTYPE}/bin
  add-paths-before-if ${HOME}/bin
fi
