#! /bin/zsh

# Provide platform-neutral functions to copy to or paste from the clipboard.

{
  if has pbcopy pbpaste; then
    if has reattach-to-user-namespace; then
      function --copy-to-clipboard()
      {
        reattach-to-user-namespace pbcopy
      }

      function --paste-from-clipboard()
      {
        reattach-to-user-namespace pbpaste
      }
    else
      function --copy-to-clipboard()
      {
        pbcopy
      }

      function --paste-from-clipboard()
      {
        pbpaste
      }
    fi
  elif has xclip; then
    function --copy-to-clipboard()
    {
      xclip -i
    }

    function --paste-from-clipboard()
    {
      xclip -o
    }
  else
    function --copy-to-clipboard()
    {
      echo >&2 "Do not know how to copy to the clipboard."
      return 1
    }

    function --paste-from-clipboard()
    {
      echo >&2 "Do not know how to paste from the clipboard."
      return 1
    }
  fi
}
