set -q KERL_BASE_DIR; or set -gx KERL_BASE_DIR $HOME/.kerl
# set KERL_CONFIGURE_OPTIONS --enable-hipe
# set KERL_CONFIGURE_DISABLE_APPLICATIONS odbc
set -gx KERL_DEFAULT_INSTALL_DIR $KERL_BASE_DIR/installs
